"""
reporting.py - Local PDF + JSON report generation
Built by MR CYBER (Harsh Saini)
"""
import json
import os
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import cm


def _watermark_canvas(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica-Bold", 40)
    canvas.setFillColor(colors.Color(0.85, 0.85, 0.85))
    canvas.translate(A4[0] / 2, A4[1] / 2)
    canvas.rotate(45)
    canvas.drawCentredString(0, 0, "MR CYBER - IOT HUNTER")
    canvas.restoreState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(2 * cm, 1 * cm, "Generated by IoT Hunter | Built by MR CYBER (Harsh Saini)")


def generate_json_report(data, report_path):
    os.makedirs(report_path, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = os.path.join(report_path, f"iothunter_report_{ts}.json")
    with open(path, "w") as f:
        json.dump(data, f, indent=2, default=str)
    return path


def generate_pdf_report(data, report_path):
    os.makedirs(report_path, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = os.path.join(report_path, f"iothunter_report_{ts}.pdf")

    doc = SimpleDocTemplate(path, pagesize=A4)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleC", parent=styles["Title"], textColor=colors.HexColor("#111111"))
    story = []

    story.append(Paragraph("IoT Hunter Security Report", title_style))
    story.append(Paragraph("Built by MR CYBER (Harsh Saini)", styles["Normal"]))
    story.append(Paragraph(f"Generated: {datetime.now().isoformat()}", styles["Normal"]))
    story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph("Executive Summary", styles["Heading2"]))
    devices = data.get("discovery", {}).get("devices", [])
    cred_hits = data.get("credential_findings", [])
    proto_hits = data.get("protocol_findings", [])
    anomalies = data.get("anomaly_findings", [])
    summary = (f"Scanned subnet {data.get('discovery', {}).get('subnet', 'N/A')}. "
               f"Discovered {len(devices)} device(s). "
               f"{len(cred_hits)} device(s) with default credentials, "
               f"{len(proto_hits)} insecure protocol instance(s), "
               f"{len(anomalies)} traffic anomaly alert(s).")
    story.append(Paragraph(summary, styles["Normal"]))
    story.append(Spacer(1, 0.5 * cm))

    if devices:
        story.append(Paragraph("Discovered Devices", styles["Heading2"]))
        table_data = [["IP", "MAC", "Vendor", "Type", "Open Ports"]]
        for d in devices:
            table_data.append([
                d.get("ip", ""), d.get("mac", ""), d.get("vendor", ""),
                d.get("device_type", "N/A"), ", ".join(map(str, d.get("open_ports", [])))
            ])
        t = Table(table_data, hAlign="LEFT")
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#222222")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.5 * cm))

    plan = data.get("remediation_plan", [])
    if plan:
        story.append(Paragraph("Remediation Plan", styles["Heading2"]))
        for item in plan:
            story.append(Paragraph(f"<b>[{item['priority'].upper()}]</b> {item['finding']}", styles["Normal"]))
            story.append(Paragraph(f"Fix: {item['fix']}", styles["Normal"]))
            for cmd in item.get("commands", []):
                story.append(Paragraph(f"&nbsp;&nbsp;&bull; <font face='Courier'>{cmd}</font>", styles["Normal"]))
            story.append(Spacer(1, 0.2 * cm))

    doc.build(story, onFirstPage=_watermark_canvas, onLaterPages=_watermark_canvas)
    return path


def generate_reports(data, report_path):
    json_path = generate_json_report(data, report_path)
    pdf_path = generate_pdf_report(data, report_path)
    return json_path, pdf_path
