#!/usr/bin/env python3
import os
import sys
import yaml
import json
from datetime import datetime

# Setup path resolution for local modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from modules.discovery import auto_detect_network, run_port_discovery
from modules.fingerprint import analyze_device_fingerprint
from modules.credentials import run_credential_audit
from modules.protocol import check_plaintext_protocols
from modules.vuln_scan import run_vuln_assessment
from modules.reporting import export_compliance_reports

def load_config():
    if os.path.exists("config.yaml"):
        try:
            with open("config.yaml", "r") as f:
                return yaml.safe_load(f) or {}
        except Exception:
            pass
    return {"network": {"target_host": "auto-detect", "scan_timeout": 1.5, "threads": 10},
            "scanners": {"rate_limit_delay": 0.1, "default_wordlist": [["admin", "admin"]]},
            "commercial_license": {"tier": "FREE_COMMUNITY", "license_key": ""}}

def show_premium_licensing_info():
    print("\n[NOTICE] ENTERPRISE GRC MODULE REQUIRES LICENSING")
    print("------------------------------------------------------------")
    print("To unlock advanced GRC reporting, network anomaly sniffing,")
    print("and automated remediation commands, an active license is required.")
    print("\nPURCHASE PROCESS:")
    print("1. Email your business inquiry to: manager.prachi@zohomail.in")
    print("2. A formal corporate invoice will be generated by Prachi Sharma.")
    print("3. Upon direct bank transfer (IMPS/NEFT), your key will be dispatched.")
    print("4. Insert the provided key into config.yaml to unlock features.")
    print("------------------------------------------------------------\n")

def main():
    os.makedirs('reports', exist_ok=True)
    config = load_config()
    tier = config.get("commercial_license", {}).get("tier", "FREE_COMMUNITY")
    
    print("\n============================================================")
    print("SYSTEM CONTROL: MR IOT HUNTER (CORE INTERFACE)")
    print("============================================================")
    print("Developer : Harsh Saini (MR CYBER)")
    print("Framework : MR CYBER PULSE")
    print("Status    : Core Audit Engine Active")
    print("------------------------------------------------------------")
    print("LEGAL NOTICE: Authorized network defensive tasks only.")
    print("============================================================")
    
    if input("\nDo you accept authorization terms and start scanning? (y/N): ").strip().lower() != 'y':
        print("[*] Task aborted by user.")
        sys.exit(0)
        
    target_host = config.get("network", {}).get("target_host", "auto-detect")
    if target_host == "auto-detect": 
        target_host = auto_detect_network()
        
    timeout = config.get("network", {}).get("scan_timeout", 1.5)
    threads = config.get("network", {}).get("threads", 10)
    wordlist = config.get("scanners", {}).get("default_wordlist", [["admin", "admin"]])
    delay = config.get("scanners", {}).get("rate_limit_delay", 0.1)
    
    print(f"\n[+] Processing Target Core IP: {target_host}")
    
    while True:
        print("\n------------------------------------------------------------")
        print("MAIN CONFIGURATION MENU")
        print("------------------------------------------------------------")
        print("1. Execute Discovery Scan & Port Probing")
        print("2. Execute Default Credential Security Check")
        print("3. Execute Plaintext Protocol Scan & Export JSON")
        print("4. Unlock Enterprise GRC Mapping (ISO 27001 / DPDP)")
        print("5. Exit Application Interface")
        print("------------------------------------------------------------")
        
        choice = input("Select an option [1-5]: ").strip()
        
        if choice == '1':
            active_ports = run_port_discovery(target_host, timeout, threads)
            analyze_device_fingerprint(target_host, active_ports)
        elif choice == '2':
            active_ports = run_port_discovery(target_host, timeout, threads)
            run_credential_audit(target_host, active_ports, wordlist, delay)
        elif choice == '3':
            active_ports = run_port_discovery(target_host, timeout, threads)
            risks = check_plaintext_protocols(active_ports)
            device_profile = analyze_device_fingerprint(target_host, active_ports)
            vulns = run_vuln_assessment(device_profile)
            
            free_data = {"target": target_host, "open_ports": active_ports, "risks": risks, "vulnerabilities": vulns}
            export_compliance_reports(tier, free_data)
        elif choice == '4':
            show_premium_licensing_info()
        elif choice == '5':
            print("\n[+] Exiting application interface.")
            sys.exit(0)
        else:
            print("[!] Invalid input selection.")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(0)
